name: Deploy Header Bidding

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm install
      - name: Build Prebid.js
        run: npm run build
      - name: Deploy to Server
        run: scp -r ./dist user@server:/path/to/ad-system
